language: node_js
node_js:
  - "13"
  - "12"
  - "11"
  - "10"
  - "8"
  - "6"
# No reason to believe the package doesn't work on these versions, but the test
# framework refuses to run on them.
#  - "9"
#  - "7"
